In [1]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]]    #It is a list of list that makes the sudoku puzzle

In [2]:
print(grid)

[[5, 3, 0, 0, 7, 0, 0, 0, 0], [6, 0, 0, 1, 9, 5, 0, 0, 0], [0, 9, 8, 0, 0, 0, 0, 6, 0], [8, 0, 0, 0, 6, 0, 0, 0, 3], [4, 0, 0, 8, 0, 3, 0, 0, 1], [7, 0, 0, 0, 2, 0, 0, 0, 6], [0, 6, 0, 0, 0, 0, 2, 8, 0], [0, 0, 0, 4, 1, 9, 0, 0, 5], [0, 0, 0, 0, 8, 0, 0, 7, 9]]


In [3]:
#since the grid is not redable

In [4]:
import numpy as np              #import numpy library
print(np.matrix(grid))          #we can print the grid for better understanding the puzzle

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


In [5]:
def possible(y,x,n):                           #This function determines that can we put a number n at any position (y,x)
    global grid                               
    for i in range(0,9):            #returns false if the number n is already present in the coloumn and it can't be placed
        if grid[y] [i] == n:
            return False
    for i in range(0,9):             #returns false if the number n is already present in the row and it can't be placed
        if grid[i][x]== n:
            return False
    xq = (x//3)* 3
    yq = (y//3)* 3
    for i in range(0,3):                    #this checks if the number is present in that 3x3 box
        for j in range(0,3):
            if grid[yq+i][xq + j] == n:
                return False
    return True                            #if all three above conditions is false then the function returns true , i.e.
                                           #the function retuns true and number n can be placed at (y,x)

In [6]:
possible(4,4,4)

False

In [7]:
possible(4,4,5)

True

In [8]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:               #this loop finds the empty position in the puzzle that will be filled
                for n in range (1,10):        #we need to check for every number at that empty position
                    if possible(y,x,n):       #if it is possible to put n at (y,x)
                        grid [y][x] = n       #place n at (y,x)
                        solve()               #as now one position is filled we can do recursion with one less empty position
                                              #now it is possible that we cannot further fill any position i.e. we have reached dead end
                                              #so here we use the concept of backtracking
                                              #Backtracking - removing the bad choices and solving again.
                        grid[y][x] = 0
                return                        #return the grid
    print(np.matrix(grid))                    #print the solution grid


In [9]:
solve()

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
